# -*- coding: utf-8 -*-
"""11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11SRnZWONTorVQJ3rHXX7hI8tfyD2rvTz
"""

import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_breast_cancer
# Load the Breast Cancer dataset
data = load_breast_cancer()
X = data.data
y = data.target
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,
random_state=42)
# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
# Define the neural network model
model = tf.keras.models.Sequential([
tf.keras.layers.Dense(1, activation='sigmoid',
input_shape=(X_train.shape[1],))
])
# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy',
metrics=['accuracy'])
# Train the model
model.fit(X_train, y_train, epochs=5)
# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", test_accuracy)